
name: continuous integration

on:
  pull_request:
    branches: [ main ]
  push:

jobs:
  install_poetry:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install Poetry
      run: Gr1N/setup-poetry@v4
