
name: continuous integration

on:
  pull_request:
    branches: [ main ]
  push:

jobs:
  install_poetry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
          
      - uses: Gr1N/setup-poetry@v7
        with:
          poetry-preview: true

      - run: poetry --version
      
  install_poetry_stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
          
      - uses: Gr1N/setup-poetry@v7
      - run: poetry --version
      

  autoformatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
          
      - uses: Gr1N/setup-poetry@v7
      - run: poetry install
      - run: poetry run black --check .
      - run: poetry run isort --check .
      
  lynting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
          
      - uses: Gr1N/setup-poetry@v7
      - run: poetry install
      - run: poetry run pylint **/*.py
    

